### ISSUE TITLE
Is this possible to run labeless on IDA PRO demo?

### ISSUE THREAD

**Issue by pawlos** [a1ext/labeless#12]
Does this tool work with IDA Pro demo version? I can see that after the build phase there are no IDA plugins files to copy (`IDA[XX]\plugins\labeless_ida.plw`, `IDA[XX]\plugins\labeless_ida.p64`) but I was rather thinking whether it is possible to make this work with the demo version of full one is required?

**Comment by a1ext** [comment]
> I can see that after the build phase there are no IDA plugins files to copy (IDA[XX]\plugins\labeless_ida.plw, IDA[XX]\plugins\labeless_ida.p64)

All the binaries will be in ```/bin``` directory after successful build.
The Labeless may run with IDA Demo, but it will be unstable because of limited functionality of IDA Demo.
Also, Labeless requires working ```IDAPython``` plugin ```python.plw``` (which ships with IDA PRO) along with ```python``` directory from IDA PRO distribution (there are important IDA SDK python wrappers) for its work.

So, to make Labeless work in IDA Demo you should perform the following things:

- Grab somewhere ```IDA PRO\plugins\python.plw``` and copy to ```IDA Demo\plugins\``` directory
- copy whole ```IDA PRO\python``` directory to ```IDA Demo``` folder
- copy ```labeless_ida_69[x].plw``` to ```IDA Demo\plugins\``` directory

![image](https://cloud.githubusercontent.com/assets/14978853/17837287/e93b97a0-67b7-11e6-88b6-eb00782fb8aa.png)

**Comment by a1ext** [comment]
So, I'll close the issue for now. If you have some questions don't hesitate to ask.

**Comment by pawlos** [comment]
Hi @a1ext,

Thx for the response.

This is the log from running the installs scripts on my machine:

`python.exe setup_protobuf.py`
https://gist.github.com/pawlos/3f4585fcaf2fc73af84f1552ee049331

`python.exe setup.py install`
https://gist.github.com/pawlos/73cf28c1032d10e9347077a3ba53d6eb

bin folder is empty (apart from .gitignore from github)
![image](https://cloud.githubusercontent.com/assets/1296768/17861560/d3c5ded2-6891-11e6-9d1b-d8d4997fe614.png)

**Comment by a1ext** [comment]
The /bin directory will contain plugins if you make them with Visual Studio. Did you build Labeless with Visual Studio?
Also, did you try to use release build instead of compilling all the plugins? [Here](https://github.com/a1ext/labeless/releases/latest) is the latest build

**Comment by pawlos** [comment]
@a1ext oh, now I get it. 
I've downloaded the repo and tried to follow the installation guide that was for the precompiled bins :)
