### ISSUE TITLE
IDA 7.0 x64 support

### ISSUE THREAD

**Issue by kolad85** [a1ext/labeless#31]
Now with the new IDA finally being x64 bit could we hope for a release that has this top plugin will support the new version?

**Comment by a1ext** [comment]
Hi @kolad85, I'll do some refactoring of the project infrasturcture first. It becames a little bit complicate to new users to understand and build the solution for different versions of IDA (different versions of VS toolchain and Qt). 
I think it will be ready soon.

**Comment by a1ext** [comment]
Hi @kolad85, here [labeless_ida_70_for_test.zip](https://github.com/a1ext/labeless/files/1318406/labeless_ida_70_for_test.zip) is test build for IDA 7, it can be unstable. You can try it right now (before I do complete release of Labeless' new version).

It would be good to receive some feedback about it.

**Comment by kolad85** [comment]
Hi a1ext,

Thanks for getting back to me so quickly and apologies for not making this
more clear. I'm having a Linux version of IDA and the provided files won't
work for me. I guess I'm in minority as compared to the rest of IDA users
but would it be possible to compile a Linux version as well? I'm happy to
provide feedback.

Again apologies for the misunderstanding.

**Comment by a1ext** [comment]
@kolad85 its ok. It will take some time. The absent of IDA Demo 7 delays linux build.

**Comment by a1ext** [comment]
@kolad85 I have few questions about the environment for IDA7 x64 you use. Could you tell me the OS ver (including release ver), IDA dependencies packages (libraries), as much as possible about how should I prepare the build environment for it.

**Comment by kolad85** [comment]
@a1ext , Standard build Linux Mint 18.2 Sonya.

**Comment by a1ext** [comment]
@kolad85 could you privatelly share the idapython bindings from your IDA distr to perform tests (IDA Demo doesn't have them) with me using this e-mail: a13x4nd3r.t@gmail.com? I need whole `python` folder and `plugins/python.so`.
Also, I've just built the plugin for Linux and due to lack of mentioned bindings (the python ext lang is unavailable and this blocks new build release).
By the way, [here (labeless_ida_70.zip)](https://github.com/a1ext/labeless/files/1335206/labeless_ida_70.zip) is the test build. The installation steps are stay same as for Labeless 1.1.2.1 for linux.

**Comment by a1ext** [comment]
Build for IDA 7 64-bit target: [here (labeless_ida_70_64.zip)](https://github.com/a1ext/labeless/files/1335251/labeless_ida_70_64.zip)

**Comment by a1ext** [comment]
@kolad85 I have bad news.
The Hex-Rays support provided me with idapython bindings for Linux, but they don't work with IDADemo because of the ABI of idapyton is incompatible with `libida.so` from IDADemo:
![image](https://user-images.githubusercontent.com/14978853/30910657-53137234-a38e-11e7-8a7e-3eb868dec0d6.png)

So, I can't perform testing on IDADemo and I don't have a license for Linux. May I ask your help with the testing of Linux build?

Thanks

**Comment by a1ext** [comment]
Possibly, if you have a problem with loading `libprotobuf.so.9`, you need to add a symlink to it:
```
ln -s libprotobuf.so libprotobuf.so.9
```

**Comment by kolad85** [comment]
@a1ext Just tested it and it seems to work :)
I will report on any issues should I encounter any. 

p.s. just now I realized hex-rays have changed the plugins' extension from .plx to .so lol   

Many thanks!

**Comment by a1ext** [comment]
> p.s. just now I realized hex-rays have changed the plugins' extension from .plx to .so lol

Yes

> Many thanks!

No problem
