### ISSUE TITLE
Binary File Sync

### ISSUE THREAD

**Issue by sisoma2** [a1ext/labeless#38]
Is it possible to add sync support for Bynary files like Shellcodes? That would be useful when debugging them without the worry to convert them to executables.
![image](https://user-images.githubusercontent.com/7660940/41294290-faf14258-6e57-11e8-8bc1-17c863c32d4b.png)

**Comment by a1ext** [comment]
There is a workaround - you could create an IDA IDB with help of Labeless and then sync your changes to the debug process instead of just opening the shellcode in IDA as binary. But this requires you have the shellcode inside some process.
To do this you have to perform the following steps:
  * create and open clean IDA IDB using `Labeless -> Load stub database...`
  * get a debugger which is paused and dubugging some process with the shellcode inside
  * setup the connection to this debugger in IDA
  * go to `Labeless -> IDADump -> Wipe all and import...`  to dump your shellcode
![image](https://user-images.githubusercontent.com/14978853/41298166-719c8faa-6e69-11e8-99d9-62f6aa2431ec.png)
  * the following dialog will appear, find out your shellcode and using right click menu set it to be imported as `RWE - read + write + execute` memory region:
![image](https://user-images.githubusercontent.com/14978853/41298468-1ab80182-6e6a-11e8-8407-59536bfed878.png)
  * and accept this dialog, after that Labeless will dump the selected memory in a newly created IDB

The new IDB will could be both 32 and 64 bit. To dump 64-code you have to open `ida64` instead of just `ida`, there will be different `Load stub database...` submenu:
![image](https://user-images.githubusercontent.com/14978853/41298739-973e466c-6e6a-11e8-8887-f77dbf920d1b.png)

P.S. You could keep multiple modules, shellcodes, data chunks in one big IDB, you just have to use different option when dumping - `Keep existing and import...`:
![image](https://user-images.githubusercontent.com/14978853/41298818-c4047446-6e6a-11e8-8c5b-4efe17258476.png)

**Comment by sisoma2** [comment]
Ok, I will do it like you said.
Thank you very much!

**Comment by a1ext** [comment]
Hey @sisoma2,
I've just turned on binary files support. It will be released in next version, but you can get a dev build right now from the build-service [Appveyor](https://ci.appveyor.com/project/a1ext/labeless/build/1.1.2.88/artifacts)

**Comment by a1ext** [comment]
Hi @sisoma2 
Cool, thanks. 
What the latest challenge did you solve? Are there some way to improve Labeless taking into account tasks from FlareOn?
